// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestAjax.Models;

public partial class Contact
{
    public long Id { get; set; }

    public string Name { get; set; }

    public string PhoneNumber { get; set; }

    public string ContactType { get; set; }

    public string Email { get; set; }

    public string Address { get; set; }

    public string Notes { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();
}