// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestAjax.Models;

public partial class TransactionSummary
{
    public int? Year { get; set; }

    public string MonthName { get; set; }

    public int? MonthNumber { get; set; }

    public string PartyName { get; set; }

    public decimal? TotalGiven { get; set; }

    public decimal? TotalReceived { get; set; }
}