// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestAjax.Models;

public partial class Transaction
{
    public long Id { get; set; }

    public long ContactId { get; set; }

    public decimal Amount { get; set; }

    public string Type { get; set; }

    public string Details { get; set; }

    public DateTime? TransactionDate { get; set; }

    public virtual Contact Contact { get; set; }
}