// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace TestAjax.Models;

public partial class UharContext : DbContext
{
    public UharContext(DbContextOptions<UharContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Contact> Contacts { get; set; }

    public virtual DbSet<MonthlyTransactionSummary> MonthlyTransactionSummaries { get; set; }

    public virtual DbSet<Transaction> Transactions { get; set; }

    public virtual DbSet<TransactionSummary> TransactionSummaries { get; set; }

    public virtual DbSet<VwActiveContactsWithBalance> VwActiveContactsWithBalances { get; set; }

    public virtual DbSet<VwDashboardSummary> VwDashboardSummaries { get; set; }

    public virtual DbSet<VwOverallBalance> VwOverallBalances { get; set; }

    public virtual DbSet<VwTotalPayable> VwTotalPayables { get; set; }

    public virtual DbSet<VwTotalReceivable> VwTotalReceivables { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Contact>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Contacts__3214EC07B4D7D9CF");

            entity.HasIndex(e => e.ContactType, "IX_Contacts_ContactType");

            entity.HasIndex(e => e.Name, "IX_Contacts_Name");

            entity.HasIndex(e => e.PhoneNumber, "IX_Contacts_PhoneNumber");

            entity.Property(e => e.Address).HasMaxLength(500);
            entity.Property(e => e.ContactType)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Customer");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.PhoneNumber).HasMaxLength(20);
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);
        });

        modelBuilder.Entity<MonthlyTransactionSummary>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("MonthlyTransactionSummary");

            entity.Property(e => e.MonthName).HasMaxLength(30);
            entity.Property(e => e.TotalGiven).HasColumnType("decimal(38, 2)");
            entity.Property(e => e.TotalReceived).HasColumnType("decimal(38, 2)");
        });

        modelBuilder.Entity<Transaction>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Transact__3214EC070BFFAE95");

            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Details).HasMaxLength(500);
            entity.Property(e => e.PhotoFileName).IsUnicode(false);
            entity.Property(e => e.TransactionDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.Contact).WithMany(p => p.Transactions)
                .HasForeignKey(d => d.ContactId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Transacti__Conta__3D5E1FD2");
        });

        modelBuilder.Entity<TransactionSummary>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("TransactionSummary");

            entity.Property(e => e.ContactType).HasMaxLength(20);
            entity.Property(e => e.MonthName).HasMaxLength(30);
            entity.Property(e => e.PartyName).HasMaxLength(150);
            entity.Property(e => e.TotalGiven).HasColumnType("decimal(38, 2)");
            entity.Property(e => e.TotalReceived).HasColumnType("decimal(38, 2)");
        });

        modelBuilder.Entity<VwActiveContactsWithBalance>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_ActiveContactsWithBalance");

            entity.Property(e => e.Balance).HasColumnType("decimal(38, 2)");
            entity.Property(e => e.ContactName)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.ContactType)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.CreatedDateFormatted).HasMaxLength(4000);
            entity.Property(e => e.DueDate)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false);
            entity.Property(e => e.LastTransactionDate).HasMaxLength(4000);
            entity.Property(e => e.PhoneNumber)
                .IsRequired()
                .HasMaxLength(20);
        });

        modelBuilder.Entity<VwDashboardSummary>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_DashboardSummary");

            entity.Property(e => e.BalanceAmount).HasColumnType("decimal(38, 2)");
            entity.Property(e => e.TotalGiven).HasColumnType("decimal(38, 2)");
            entity.Property(e => e.TotalReceived).HasColumnType("decimal(38, 2)");
        });

        modelBuilder.Entity<VwOverallBalance>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_OverallBalance");

            entity.Property(e => e.NetBalance).HasColumnType("decimal(38, 2)");
            entity.Property(e => e.TotalGiven).HasColumnType("decimal(38, 2)");
            entity.Property(e => e.TotalReceived).HasColumnType("decimal(38, 2)");
        });

        modelBuilder.Entity<VwTotalPayable>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_TotalPayable");

            entity.Property(e => e.TotalPayable).HasColumnType("decimal(38, 2)");
        });

        modelBuilder.Entity<VwTotalReceivable>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_TotalReceivable");

            entity.Property(e => e.TotalReceivable).HasColumnType("decimal(38, 2)");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}