// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestAjax.Models;

public partial class VwActiveContactsWithBalance
{
    public long ContactId { get; set; }

    public string ContactName { get; set; }

    public string PhoneNumber { get; set; }

    public string CreatedDateFormatted { get; set; }

    public string DueDate { get; set; }

    public string ContactType { get; set; }

    public string LastTransactionDate { get; set; }

    public decimal Balance { get; set; }
}