// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestAjax.Models;

public partial class VwDashboardSummary
{
    public int? TotalAccounts { get; set; }

    public int? TotalCustomers { get; set; }

    public int? TotalSuppliers { get; set; }

    public int? ActiveAccounts { get; set; }

    public decimal? TotalGiven { get; set; }

    public decimal? TotalReceived { get; set; }

    public decimal? BalanceAmount { get; set; }
}