// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestAjax.Models;

public partial class VwOverallBalance
{
    public decimal? TotalGiven { get; set; }

    public decimal? TotalReceived { get; set; }

    public decimal? NetBalance { get; set; }
}